using UnityEngine;

namespace Bloodfall.Client.Core
{
    public enum CursorKind { Default, Attack, Cast, Ally }

    /// <summary>Hardware cursors (gauntlet / sword / rune) generated by Tools/art/generate_ui.py.</summary>
    public static class CursorManager
    {
        private static CursorKind _current = (CursorKind)(-1);
        private static readonly Texture2D[] Cache = new Texture2D[4];

        public static void Apply(CursorKind kind)
        {
            if (kind == _current) return;
            _current = kind;
            int i = (int)kind;
            if (Cache[i] == null)
            {
                string name = kind == CursorKind.Attack ? "cursor_attack" : kind == CursorKind.Cast ? "cursor_cast" : kind == CursorKind.Ally ? "cursor_ally" : "cursor_default";
                Cache[i] = Resources.Load<Texture2D>("Textures/UI/Cursors/" + name);
            }
            var hotspot = kind == CursorKind.Cast ? new Vector2(15, 15) : kind == CursorKind.Attack ? new Vector2(2, 2) : Vector2.zero;
            if (Cache[i] != null) Cursor.SetCursor(Cache[i], hotspot, CursorMode.Auto);
        }
    }
}
